name: hisaab
description: "keep track of transactions"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  intl: ^0.18.1
  file_picker: ^10.3.6
  crop_your_image: ^0.7.0
  qr_flutter: ^4.0.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.9.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Constance
      fonts:
        - asset: assets/fonts/Constance.ttf

    - family: Moldern
      fonts:
        - asset: assets/fonts/Moldern.ttf
    
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay.ttf

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "assets/background.png"
  adaptive_icon_foreground: "assets/foreground.png"
  image_path: "assets/icon.png"
  image_path_ios: "assets/icon.png"